import{S as m,i as l}from"./assets/vendor-5b791d57.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))t(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&t(a)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function t(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const p=document.querySelector("input");p.value.trim();document.querySelector(".gallery");function f(n){const s=`https://pixabay.com/api/?${new URLSearchParams({key:"43047953-84179c8300fd9f33658a206cf",q:n,image_type:"photo",orientation:"horizontal",safesearch:"true"})}`;return fetch(s).then(t=>{if(!t.ok)throw new Error(t.status);return t.json()})}const h=document.querySelector(".gallery");function g(n){if(n.length==0)l.error({title:"Error",message:"❌ Sorry, there are no images matching your search query. Please, try again!",theme:"dark",progressBarColor:"#FFFFFF",color:"#EF4040",position:"topRight"});else{const o=n.map(t=>`<li class="photos-list-item">
        <a class="photos-list-link" href="${t.largeImageURL}">
        <img class="photo" src="${t.webformatURL}" alt="${t.tags}"/>
        </a>
        <ul class="photo-information-container">
        <li class="item-photo-information-container"><p><span class="accent">Likes</span></br>${t.likes}</p></li>
        <li class="item-photo-information-container"><p><span class="accent">Views</span></br>${t.views}</p></li>
        <li class="item-photo-information-container"><p><span class="accent">Comments</span></br>${t.comments}</p></li>
        <li class="item-photo-information-container"><p><span class="accent">Downloads</span></br>${t.downloads}</p></li>
        </ul>
        </li>`).join("");h.insertAdjacentHTML("beforeend",o),new m(".gallery a",{captionsData:"alt"}).refresh()}}const d=new m(".gallery a",{});d.refresh();const c=document.querySelector(".gallery");let i;const u=document.querySelector("input"),y=document.querySelector("button");u.addEventListener("input",()=>{i=u.value.trim(),c.innerHTML=""});y.addEventListener("click",n=>{n.preventDefault(),i===""&&(l.error({color:"yellow",message:" Please fill in the field for search",position:"topRight"}),c.innerHTML=""),i&&f(i).then(o=>g(o.hits)).catch(o=>{console.log(o),l.error({title:"Error",message:"❌ Sorry, there are no images matching your search query. Please, try again!",position:"topRight"})}),c.innerHTML=""});
//# sourceMappingURL=commonHelpers.js.map
