import{S as c,i as l}from"./assets/vendor-5b791d57.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))r(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&r(i)}).observe(document,{childList:!0,subtree:!0});function n(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function r(e){if(e.ep)return;e.ep=!0;const t=n(e);fetch(e.href,t)}})();const m=document.querySelector(".gallery");function p(){const o=new URLSearchParams({key:"43047953-84179c8300fd9f33658a206cf"});m.innerHTML='<span class="loader"></span>';const s=`https://pixabay.com/api/?${o}`;return fetch(s).then(n=>{if(!n.ok)throw new Error(n.status);return n.json()})}const f=document.querySelector(".gallery");function d(o){if(o.length==0)l.error({title:"Error",message:"❌ Sorry, there are no images matching your search query. Please, try again!",theme:"dark",progressBarColor:"#FFFFFF",color:"#EF4040",position:"topRight"});else{const s=o.map(r=>`<li class="photos-list-item">
        <a class="photos-list-link" href="${r.largeImageURL}">
        <img class="photo" src="${r.webformatURL}" alt="${r.tags}"/>
        </a>
        <ul class="photo-information-container">
        <li class="item-photo-information-container"><p><span class="accent">Likes</span></br>${r.likes}</p></li>
        <li class="item-photo-information-container"><p><span class="accent">Views</span></br>${r.views}</p></li>
        <li class="item-photo-information-container"><p><span class="accent">Comments</span></br>${r.comments}</p></li>
        <li class="item-photo-information-container"><p><span class="accent">Downloads</span></br>${r.downloads}</p></li>
        </ul>
        </li>`).join("");f.insertAdjacentHTML("beforeend",s),new c(".gallery a",{captionsData:"alt"}).refresh()}}const g=new c(".gallery a",{});g.refresh();document.querySelector(".gallery");let u;const a=document.querySelector("input"),h=document.querySelector("button");a.addEventListener("input",()=>{u=a.value.trim()});h.addEventListener("click",()=>{u&&p().then(o=>d(o.hits)).catch(o=>{console.log(o),l.error({title:"Error",message:"❌ Sorry, there are no images matching your search query. Please, try again!",position:"topRight"})})});
//# sourceMappingURL=commonHelpers.js.map
